### ISSUE TITLE
Обращение массива

### ISSUE THREAD

**Issue by khda91** [AlexanderKovalev1989/MyProjects#4]
https://github.com/AlexanderKovalev1989/MyProjects/blob/fdd70785923be4719cff811e009d2e085e0bd936/src/Triangle/OthersHomeworks/ReverseArray.java#L44

Должен ли быть данный метод void? Сейчас Вы просто выводите данный массив наоборот)

**Comment by AlexanderKovalev1989** [comment]
"Написать программу, которая переворачивает заданный список (массив)
наоборот." тут имелось ввиду что перевернутый массив должен быть возвращен?

**Comment by khda91** [comment]
Да, перевёрнутый массив должен возвращаться

**Comment by AlexanderKovalev1989** [comment]
https://github.com/AlexanderKovalev1989/MyProjects/blob/ced906a5f6c8f3701db74e5de868ce7805121cf7/src/Triangle/OthersHomeworks/ReverseArray.java#L51

поправил
