### ISSUE TITLE
before statement - можно удалить

### ISSUE THREAD

**Issue by khda91** [AlexanderKovalev1989/MyProjects#8]
https://github.com/AlexanderKovalev1989/MyProjects/blob/ada0a0f0067e430b26dde0364fb4aeea8c4c06d9/src/AirCompany/src/test/java/PlaneComparatorTest.java#L15

Можно удалить данный метод, так как он не несет никаких действий по настройке тестового контекста

**Comment by AlexanderKovalev1989** [comment]
done

**Comment by AlexanderKovalev1989** [comment]
done
